// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzlWCp69G3qv2CSw-SUnWhSfSc_5UTT_U',
    appId: '1:1047849270281:web:236124524ebf9fda3dccd8',
    messagingSenderId: '1047849270281',
    projectId: 'ocean-tech-be9a8',
    authDomain: 'ocean-tech-be9a8.firebaseapp.com',
    storageBucket: 'ocean-tech-be9a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2X8t-GU6tO74CXwuP8qQt7ZEG01fnJJ0',
    appId: '1:998896689837:android:11a968463a090ff1011c24',
    messagingSenderId: '998896689837',
    projectId: 'learning-english-6441b',
    storageBucket: 'learning-english-6441b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJfB0qfzoQPU6t3YKWrSA1WhRClyAezZo',
    appId: '1:1047849270281:ios:659a582f6c0b3eb13dccd8',
    messagingSenderId: '1047849270281',
    projectId: 'ocean-tech-be9a8',
    storageBucket: 'ocean-tech-be9a8.firebasestorage.app',
    iosBundleId: 'com.example.flutterOceantech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJfB0qfzoQPU6t3YKWrSA1WhRClyAezZo',
    appId: '1:1047849270281:ios:659a582f6c0b3eb13dccd8',
    messagingSenderId: '1047849270281',
    projectId: 'ocean-tech-be9a8',
    storageBucket: 'ocean-tech-be9a8.firebasestorage.app',
    iosBundleId: 'com.example.flutterOceantech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9QNb1gTSPUey0cKLJQD3dABjvoVJuH3M',
    appId: '1:998896689837:web:2d2d8f6d32d36a23011c24',
    messagingSenderId: '998896689837',
    projectId: 'learning-english-6441b',
    authDomain: 'learning-english-6441b.firebaseapp.com',
    storageBucket: 'learning-english-6441b.appspot.com',
  );

}